name: Build

# Trigger the workflow on any push and when a release is published
on:
  push: 
    branches: ['feature/ci']
    
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: git fetch --prune --unshallow
      
      - name: generate version.json
        run: |-
          git describe --tags | sed 's/^v//; s/-.*//' | jq -R 'split(".") | {major: .[0]|tonumber, minor: .[1]|tonumber, patch: .[2]|tonumber}' > version.json
      - name: generate zip
        run: zip -9 -r miriani-next.zip . --exclude=*.git*
      - name: Upload zip
        uses: actions/upload-artifact@v4C
        with:
          name: miriani-next
          path: ./miriani-next.zip
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags') && github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          artifacts: './miriani-next'
          draft: true
          generateReleaseNotes: true
